import { addDays, differenceInCalendarDays, format, parseISO } from "date-fns";
import type { AppData, Cycle, DailyLog, HabitDefinition } from "./types";
export const CYCLE_START = "2026-08-15";
export const CYCLE_END = "2026-12-04";
export const weekThemes = ["Set the standard", "Protect the rhythm", "Build momentum", "Raise the output", "Make it repeatable", "Sharpen the edge", "Ship the work", "Hold the line", "Compound the proof", "Move the needle", "Finish what matters", "Make discipline visible", "Turn skill into leverage", "Close the loop", "Sprint with control", "Finish locked in"];
const habitNames: Array<[string, string, "health" | "discipline" | "mind" | "business"]> = [["morning-meds","Morning medication","health"],["night-meds","Night medication","health"],["cold-shower","Cold shower","health"],["healthy-breakfast","Healthy breakfast","health"],["healthy-lunch","Healthy lunch","health"],["healthy-dinner","Healthy dinner","health"],["morning-detox","No scrolling — first hour","discipline"],["social-limit","Social media within limit","discipline"],["night-detox","No scrolling before bed","discipline"],["top-three","Today’s Big 3","discipline"],["daily-review","Daily review","discipline"],["bible","Bible reading","mind"],["reading","Book reading","mind"],["learning","Learning completed","mind"],["business-work","Business deep work","business"],["outreach","Client outreach","business"],["project-work","Website / project work","business"],["follow-ups","Prospect follow-ups","business"]];
export const defaultHabits: HabitDefinition[] = habitNames.map(([id,name,category],order) => ({ id,name,category,weekdays:[0,1,2,3,4,5,6],weight:1,hidden:false,order }));
export function generateCycle(startDate: string, weeks: number, name = "LOCKED IN — CYCLE 1"): Cycle { const start=parseISO(startDate); return { id:`cycle-${startDate}`,name,startDate,endDate:format(addDays(start,weeks*7-1),"yyyy-MM-dd"),weeks,themes:Array.from({length:weeks},(_,i)=>weekThemes[i%weekThemes.length]) }; }
export function generateDailyLogs(cycle: Cycle): DailyLog[] { const start=parseISO(cycle.startDate); const days=differenceInCalendarDays(parseISO(cycle.endDate),start)+1; return Array.from({length:days},(_,index)=>{ const date=addDays(start,index); return { id:`${cycle.id}-${format(date,"yyyy-MM-dd")}`,cycleId:cycle.id,date:format(date,"yyyy-MM-dd"),dayNumber:index+1,weekNumber:Math.floor(index/7)+1,weekday:date.getDay(),completions:{},priorities:[1,2,3].map(n=>({id:`p${n}`,title:"",category:"Personal",estimatedMinutes:60,actualMinutes:0,notes:"",completed:false})),waterMl:0,sleepHours:0,sleepQuality:0,fitness:{completed:false,type:"rest",durationMinutes:0,notes:""},meals:{breakfast:{ate:false,healthy:false},lunch:{ate:false,healthy:false},dinner:{ate:false,healthy:false}},socialMinutes:0,businessMinutes:0,learningMinutes:0,readingMinutes:0,bibleMinutes:0,outreach:{sent:0,followUps:0,calls:0,responses:0,meetings:0,proposals:0,closed:0},reflection:"" }; }); }
export function createSeedData(): AppData { const cycle=generateCycle(CYCLE_START,16); return { version:1,settings:{name:"Andrei",theme:"dark",currency:"GBP",timezone:"Europe/London",firstDayOfWeek:1,waterTargetMl:2500,sleepTargetHours:8,socialLimitMinutes:30,fitnessWeeklyTarget:4,readingDailyMinutes:20,businessWeeklyHours:10,outreachWeeklyTarget:25,learningWeeklySessions:4,onboardingComplete:false},cycles:[cycle],habits:defaultHabits,dailyLogs:generateDailyLogs(cycle),clients:[],projects:[],expenses:[],income:[],goals:[{id:"m4",name:"BMW M4 F82",label:"SHORT–MEDIUM TERM GOAL",target:30000,accent:"cyan",currency:"GBP"},{id:"romania",name:"MOVE PERMANENTLY TO ROMANIA",label:"~24 MONTH MISSION",target:20000,targetDate:"2028-08-15",accent:"amber",currency:"GBP"}],contributions:[],ideas:[],appointments:[],focusSessions:[],readingSessions:[],learningTracks:[{id:"ibm",name:"IBM Full Stack Software Developer",category:"Full Stack Cloud Development",progress:0,hours:0,courseUrl:"https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer"},{id:"web-ai",name:"Web Development & AI",category:"Skill matrix",progress:0,hours:0,skills:Object.fromEntries(["HTML","CSS","JavaScript","TypeScript","React","Next.js","APIs","Databases","Git","Deployment","Three.js","AI integrations"].map(skill=>[skill,0]))}],weeklyReviews:[] }; }
