"use client";
import { format, parseISO } from "date-fns";
import { Activity, BookMarked, BriefcaseBusiness, Droplets, Moon, Plus, Utensils } from "lucide-react";
import { useApp } from "@/components/AppProvider";
import { CheckButton, Eyebrow, Panel, ProgressBar, ProgressRing } from "@/components/ui";
import { calculateScore } from "@/lib/metrics";
import type { Category, DailyLog } from "@/lib/types";
const categories:Category[]=["health","discipline","mind","business"];
export function TodayPage(){const{data,updateLog}=useApp();const key=new Date().toISOString().slice(0,10);const log=data.dailyLogs.find(l=>l.date===key)??data.dailyLogs[0];const patch=(recipe:(log:DailyLog)=>DailyLog)=>updateLog(log.id,recipe);const score=calculateScore(log,data.habits,data.settings.waterTargetMl,data.settings.sleepTargetHours);const coldTarget=Math.min(120,30+(log.weekNumber-1)*15);
 return <div className="page today-page"><header className="page-title today-title"><div><Eyebrow>DAY {log.dayNumber} / 112 · WEEK {log.weekNumber}</Eyebrow><h1>{format(parseISO(log.date),"EEEE")} <i>{format(parseISO(log.date),"dd MMM")}</i></h1><p>{score>0?"Progress made today. Keep building.":"The plan is ready. Make the first move."}</p></div><ProgressRing value={score} size={142}/></header>
 <Panel accent className="big-three"><div className="panel-heading"><div><Eyebrow>EXECUTION FIRST</Eyebrow><h2>TODAY’S BIG 3</h2></div><span>{log.priorities.filter(p=>p.completed).length} / 3 COMPLETE</span></div><div className="priority-list">{log.priorities.map((priority,index)=><div className={`priority ${priority.completed?"done":""}`} key={priority.id}><button onClick={()=>patch(l=>({...l,priorities:l.priorities.map(p=>p.id===priority.id?{...p,completed:!p.completed}:p)}))} aria-label={`Toggle priority ${index+1}`}>{priority.completed?"✓":String(index+1).padStart(2,"0")}</button><div><label htmlFor={`priority-${index}`}>PRIORITY {index+1}</label><input id={`priority-${index}`} value={priority.title} placeholder={index===0?"What must move forward today?":"Add a concrete outcome"} onChange={e=>patch(l=>({...l,priorities:l.priorities.map(p=>p.id===priority.id?{...p,title:e.target.value}:p)}))}/></div><select value={priority.category} onChange={e=>patch(l=>({...l,priorities:l.priorities.map(p=>p.id===priority.id?{...p,category:e.target.value}:p)}))}><option>Personal</option><option>Business</option><option>Learning</option><option>Health</option></select></div>)}</div></Panel>
 <div className="today-grid"><Panel className="habit-panel"><div className="panel-heading"><div><Eyebrow>DAILY PROTOCOL</Eyebrow><h3>Habits</h3></div><Activity/></div>{categories.map(category=><div className="habit-group" key={category}><span>{category}</span><div>{data.habits.filter(h=>h.category===category&&!h.hidden).map(h=><CheckButton key={h.id} label={h.name} checked={!!log.completions[h.id]} onClick={()=>patch(l=>({...l,completions:{...l.completions,[h.id]:!l.completions[h.id]}}))}/>)}</div></div>)}</Panel>
 <div className="tracker-stack"><Panel className="tracker water"><div className="tracker-head"><div><Droplets/><span><Eyebrow>HYDRATION</Eyebrow><strong>{(log.waterMl/1000).toFixed(2)}L <small>/ {(data.settings.waterTargetMl/1000).toFixed(1)}L</small></strong></span></div><b>{Math.min(100,Math.round(log.waterMl/data.settings.waterTargetMl*100))}%</b></div><ProgressBar value={log.waterMl} max={data.settings.waterTargetMl}/><div className="quick-buttons"><button onClick={()=>patch(l=>({...l,waterMl:l.waterMl+250}))}><Plus/>250ml</button><button onClick={()=>patch(l=>({...l,waterMl:l.waterMl+500}))}><Plus/>500ml</button><button onClick={()=>patch(l=>({...l,waterMl:Math.max(0,l.waterMl-250)}))}>− Undo</button></div></Panel>
 <Panel className="tracker"><div className="tracker-head"><div><Moon/><span><Eyebrow>RECOVERY</Eyebrow><strong>{log.sleepHours||"—"} <small>hours slept</small></strong></span></div></div><label className="range-label">Sleep duration <input type="range" min="0" max="12" step="0.25" value={log.sleepHours} onChange={e=>patch(l=>({...l,sleepHours:Number(e.target.value)}))}/><span>{log.sleepHours}h</span></label></Panel>
 <Panel className="tracker"><div className="tracker-head"><div><Activity/><span><Eyebrow>TRAINING</Eyebrow><strong>{log.fitness.completed?log.fitness.type.toUpperCase():"REST / SELECT"}</strong></span></div></div><div className="segmented">{["gym","cardio","walk","mobility","rest"].map(type=><button className={log.fitness.type===type?"active":""} key={type} onClick={()=>patch(l=>({...l,fitness:{...l.fitness,type:type as DailyLog["fitness"]["type"],completed:type!=="rest"}}))}>{type}</button>)}</div></Panel>
 <Panel className="tracker"><div className="tracker-head"><div><Utensils/><span><Eyebrow>FOOD</Eyebrow><strong>{Object.values(log.meals).filter(m=>m.healthy).length} / 3 healthy meals</strong></span></div></div><div className="meal-row">{Object.entries(log.meals).map(([meal,value])=><button key={meal} className={value.healthy?"active":""} onClick={()=>patch(l=>({...l,meals:{...l.meals,[meal]:{ate:!value.healthy,healthy:!value.healthy}}}))}>{meal}<b>{value.healthy?"✓":"○"}</b></button>)}</div></Panel>
 <Panel className="tracker cold"><div className="tracker-head"><div><BookMarked/><span><Eyebrow>COLD SHOWER</Eyebrow><strong>Today’s target: {coldTarget}s</strong></span></div></div><button className="button secondary" onClick={()=>patch(l=>({...l,completions:{...l.completions,"cold-shower":!l.completions["cold-shower"]}}))}>{log.completions["cold-shower"]?"Completed ✓":"Start timer · Mark complete"}</button></Panel></div>
 <Panel className="execution-panel"><div className="panel-heading"><div><Eyebrow>BUSINESS EXECUTION</Eyebrow><h3>Build leverage.</h3></div><BriefcaseBusiness/></div><label>Deep work minutes<input type="number" min="0" value={log.businessMinutes||""} placeholder="0" onChange={e=>patch(l=>({...l,businessMinutes:Number(e.target.value)}))}/></label><div className="outreach-grid">{Object.entries(log.outreach).map(([key,value])=><label key={key}>{key.replace(/([A-Z])/g," $1")}<input type="number" min="0" value={value||""} placeholder="0" onChange={e=>patch(l=>({...l,outreach:{...l.outreach,[key]:Number(e.target.value)}}))}/></label>)}</div><label>Reflection<textarea value={log.reflection} placeholder="What worked? What changes tomorrow?" onChange={e=>patch(l=>({...l,reflection:e.target.value}))}/></label></Panel>
 </div></div>}
