"use client";
import Image from "next/image";
import { format, parseISO } from "date-fns";
import { ArrowUpRight, Banknote, BookOpen, BriefcaseBusiness, Dumbbell, ShieldCheck, Target } from "lucide-react";
import { useApp } from "@/components/AppProvider";
import { Eyebrow, Metric, Panel, ProgressBar, ProgressRing } from "@/components/ui";
import { calculateScore, currentStreak, goalSaved, totals } from "@/lib/metrics";
import { currencyOf, formatMoney } from "@/lib/money";
export function CommandCentre({onNavigate}:{onNavigate:(page:string)=>void}){const{data}=useApp();const cycle=data.cycles[0];const todayKey=new Date().toISOString().slice(0,10);const log=data.dailyLogs.find(l=>l.date===todayKey)??data.dailyLogs[0];const score=calculateScore(log,data.habits,data.settings.waterTargetMl,data.settings.sleepTargetHours);const finance=totals(data);const m4=data.goals.find(g=>g.id==="m4")!;const romania=data.goals.find(g=>g.id==="romania")!;const m4Saved=goalSaved(data,"m4"),romaniaSaved=goalSaved(data,"romania");const completed=data.dailyLogs.filter(l=>calculateScore(l,data.habits)>0);const overall=completed.length?Math.round(completed.reduce((s,l)=>s+calculateScore(l,data.habits),0)/completed.length):0;
 return <div className="page dashboard"><header className="page-title command-title"><div><Eyebrow>PERSONAL OPERATING SYSTEM / CYCLE 01</Eyebrow><h1>LOCKED <i>IN</i></h1><p>Use this overview to see today’s execution, cycle progress, goals, money, and momentum at a glance.</p></div><div className="cycle-counter"><span>DAY</span><strong>{String(log.dayNumber).padStart(3,"0")}</strong><em>/ 112</em></div></header>
 <div className="dashboard-grid"><Panel accent className="score-panel"><div><Eyebrow>TODAY / {format(parseISO(log.date),"EEEE, dd MMM")}</Eyebrow><h2>Make the day<br/>count twice.</h2><button className="text-link" onClick={()=>onNavigate("today")}>Open today’s protocol <ArrowUpRight size={16}/></button></div><ProgressRing value={score}/></Panel>
 <Panel className="week-panel"><div className="panel-heading"><div><Eyebrow>WEEK {String(log.weekNumber).padStart(2,"0")}</Eyebrow><h3>{cycle.themes[log.weekNumber-1]??"Stay in motion"}</h3></div><span>{112-log.dayNumber} DAYS REMAIN</span></div><ProgressBar value={log.dayNumber} max={112}/><div className="week-stats"><Metric label="Cycle adherence" value={`${overall}%`}/><Metric label="Current streak" value={`${currentStreak(data.dailyLogs,data.habits)}d`}/><Metric label="Proof recorded" value={`${completed.length} days`}/></div></Panel>
 <Panel className="goal-card m4 m4-visual"><div className="m4-copy"><div><Eyebrow>{m4.label}</Eyebrow><h3>{m4.name}</h3></div><div className="goal-money"><strong>{formatMoney(m4Saved,currencyOf(m4.currency))}</strong><span>/ {formatMoney(m4.target,currencyOf(m4.currency))}</span></div><ProgressBar value={m4Saved} max={m4.target}/><small>{Math.round(m4Saved/m4.target*100)||0}% funded · Every invoice creates options.</small></div><div className="m4-image"><Image src="/images/bmw-m4-f82.png" alt="Black BMW M4 F82 in a misty forest" fill sizes="(max-width: 760px) 100vw, 24vw" priority/></div></Panel>
 <Panel className="goal-card romania"><div><Eyebrow>{romania.label}</Eyebrow><h3>ROMANIA</h3></div><div className="goal-money"><strong>{formatMoney(romaniaSaved,currencyOf(romania.currency))}</strong><span>/ {formatMoney(romania.target,currencyOf(romania.currency))}</span></div><ProgressBar value={romaniaSaved} max={romania.target}/><small>Finance · Business · Career · Logistics · Personal</small></Panel>
 <Panel className="numbers-panel"><div className="panel-heading"><div><Eyebrow>THE NUMBERS</Eyebrow><h3>Proof, not promises.</h3></div><button className="text-link" onClick={()=>onNavigate("progress")}>See analysis <ArrowUpRight size={15}/></button></div><div className="metric-grid"><Metric label={`Revenue · ${data.settings.currency}`} value={formatMoney(finance.income,data.settings.currency)} detail="Cycle total" accent/><Metric label="Business hours" value={`${Math.round(data.dailyLogs.reduce((s,l)=>s+l.businessMinutes,0)/60)}h`}/><Metric label="Training" value={data.dailyLogs.filter(l=>l.fitness.completed&&l.fitness.type!=="rest").length}/><Metric label="Learning" value={`${Math.round(data.dailyLogs.reduce((s,l)=>s+l.learningMinutes,0)/60)}h`}/></div></Panel>
 <Panel className="needle-panel"><div className="panel-heading"><div><Eyebrow>WHAT MOVES THE NEEDLE?</Eyebrow><h3>Discipline → freedom</h3></div><Target size={20}/></div><div className="needle-list"><div><Banknote/><span><b>M4</b>Revenue · Clients · Savings</span></div><div><BriefcaseBusiness/><span><b>ROMANIA</b>Remote income · Skills · Systems</span></div><div><ShieldCheck/><span><b>PERSONAL</b>Health · Discipline · Knowledge · Faith</span></div></div></Panel>
 </div><footer className="manifesto"><div><Dumbbell/><BookOpen/></div><strong>112 days.</strong><span>One day at a time.</span><p>Build the skills. Build the business. Build the freedom.</p><b>LOCKED IN.</b></footer></div>}
